### ISSUE TITLE
Parametres du login 

### ISSUE THREAD

**Issue by winny79** [Tiththa/school-management-system#2]
Bonjour s'il vous plait pouvez vous m 'aidez pour le login je ne retrouve pas les paramètres de connexion pour accéder au dashboard.Merci

**Comment by Tiththa** [comment]
@winny79  Bonjour, Vous devez initialiser la base de données et vous avez les informations concernant les utilisateurs et les informations d'identification [**ici**](https://github.com/Tiththa/school-management-system/tree/master/database/seeds)
