### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by naszirah** [Tiththa/school-management-system#3]
Why i cannot login using email and password fake in database? It go to login page every time i enter the email and password from db

**Comment by Tiththa** [comment]
if you have seeded the database you can login with the password 'password' mentioned in  `seeds/UsersTableSeeder` @naszirah

**Comment by TANNKOANO** [comment]
Thanks for this project. I like the concept. I will keep working on it to add feature. Do you have the full project on sale?
Thanks

**Comment by Tiththa** [comment]
@TANNKOANO I have not completed this project unfortunately.  Pull requests are welcome

**Comment by TANNKOANO** [comment]
Thank you so much @naszirah zirah.
Any way, i will work on it with your permission.
