### ISSUE TITLE
System is not running.

### ISSUE THREAD

**Issue by ahmedTareque** [Tiththa/school-management-system#4]
![image](https://user-images.githubusercontent.com/16764227/61328040-09f3fd80-a83c-11e9-8856-24f799488b99.png)

### Uncaught SyntaxError: Unexpected token < 

Can you please help me out here?

**Comment by Tiththa** [comment]
@Tareque2208  I wonder whats wrong  ,it works well without errors, have you tried cloning again without editing any of the files? perhaps you might have added a < somewhere

**Comment by ahmedTareque** [comment]
![image](https://user-images.githubusercontent.com/16764227/61991236-4b23b300-b06f-11e9-980a-832bc20bf9fe.png)

Were you trying to do something with google calender? I just cloned and got this error.

**Comment by Tiththa** [comment]
@Tareque2208  yes, i was trying to setup the gcalendar api and get all the information about the logged events. you can implement it. You can comment it out if you want.I have only shared the embed calendar
